// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"store/service/internal/biz"
	"store/service/internal/conf"
	"store/service/internal/data"
	"store/service/internal/server"
	"store/service/internal/service"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.ConnectDB(confData, logger)
	dataData, cleanup, err := data.NewData(confData, db, logger)
	if err != nil {
		return nil, nil, err
	}
	storeRepo := data.NewStoreRepo(dataData, logger)
	storeUseCase := biz.NewStoreUseCase(storeRepo, logger)
	store := service.NewStore(storeUseCase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, store)
	registrar := server.NewRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
