// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/store/service/v1/store.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateGoodsReq struct {
	GoodsName            string   `protobuf:"bytes,1,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	GoodsDetail          string   `protobuf:"bytes,2,opt,name=goods_detail,json=goodsDetail,proto3" json:"goods_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGoodsReq) Reset()         { *m = CreateGoodsReq{} }
func (m *CreateGoodsReq) String() string { return proto.CompactTextString(m) }
func (*CreateGoodsReq) ProtoMessage()    {}
func (*CreateGoodsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b63c4ddc3f3c0c, []int{0}
}

func (m *CreateGoodsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGoodsReq.Unmarshal(m, b)
}
func (m *CreateGoodsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGoodsReq.Marshal(b, m, deterministic)
}
func (m *CreateGoodsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGoodsReq.Merge(m, src)
}
func (m *CreateGoodsReq) XXX_Size() int {
	return xxx_messageInfo_CreateGoodsReq.Size(m)
}
func (m *CreateGoodsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGoodsReq.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGoodsReq proto.InternalMessageInfo

func (m *CreateGoodsReq) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *CreateGoodsReq) GetGoodsDetail() string {
	if m != nil {
		return m.GoodsDetail
	}
	return ""
}

type CreateGoodsRsp struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateGoodsRsp) Reset()         { *m = CreateGoodsRsp{} }
func (m *CreateGoodsRsp) String() string { return proto.CompactTextString(m) }
func (*CreateGoodsRsp) ProtoMessage()    {}
func (*CreateGoodsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b63c4ddc3f3c0c, []int{1}
}

func (m *CreateGoodsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateGoodsRsp.Unmarshal(m, b)
}
func (m *CreateGoodsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateGoodsRsp.Marshal(b, m, deterministic)
}
func (m *CreateGoodsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateGoodsRsp.Merge(m, src)
}
func (m *CreateGoodsRsp) XXX_Size() int {
	return xxx_messageInfo_CreateGoodsRsp.Size(m)
}
func (m *CreateGoodsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateGoodsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CreateGoodsRsp proto.InternalMessageInfo

func (m *CreateGoodsRsp) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

type IncGoodsNumReq struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsNum             int64    `protobuf:"varint,2,opt,name=goods_num,json=goodsNum,proto3" json:"goods_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncGoodsNumReq) Reset()         { *m = IncGoodsNumReq{} }
func (m *IncGoodsNumReq) String() string { return proto.CompactTextString(m) }
func (*IncGoodsNumReq) ProtoMessage()    {}
func (*IncGoodsNumReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b63c4ddc3f3c0c, []int{2}
}

func (m *IncGoodsNumReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncGoodsNumReq.Unmarshal(m, b)
}
func (m *IncGoodsNumReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncGoodsNumReq.Marshal(b, m, deterministic)
}
func (m *IncGoodsNumReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncGoodsNumReq.Merge(m, src)
}
func (m *IncGoodsNumReq) XXX_Size() int {
	return xxx_messageInfo_IncGoodsNumReq.Size(m)
}
func (m *IncGoodsNumReq) XXX_DiscardUnknown() {
	xxx_messageInfo_IncGoodsNumReq.DiscardUnknown(m)
}

var xxx_messageInfo_IncGoodsNumReq proto.InternalMessageInfo

func (m *IncGoodsNumReq) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *IncGoodsNumReq) GetGoodsNum() int64 {
	if m != nil {
		return m.GoodsNum
	}
	return 0
}

type IncGoodsNumRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IncGoodsNumRsp) Reset()         { *m = IncGoodsNumRsp{} }
func (m *IncGoodsNumRsp) String() string { return proto.CompactTextString(m) }
func (*IncGoodsNumRsp) ProtoMessage()    {}
func (*IncGoodsNumRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b63c4ddc3f3c0c, []int{3}
}

func (m *IncGoodsNumRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IncGoodsNumRsp.Unmarshal(m, b)
}
func (m *IncGoodsNumRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IncGoodsNumRsp.Marshal(b, m, deterministic)
}
func (m *IncGoodsNumRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IncGoodsNumRsp.Merge(m, src)
}
func (m *IncGoodsNumRsp) XXX_Size() int {
	return xxx_messageInfo_IncGoodsNumRsp.Size(m)
}
func (m *IncGoodsNumRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_IncGoodsNumRsp.DiscardUnknown(m)
}

var xxx_messageInfo_IncGoodsNumRsp proto.InternalMessageInfo

type DecGoodsNumReq struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsNum             int64    `protobuf:"varint,2,opt,name=goods_num,json=goodsNum,proto3" json:"goods_num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecGoodsNumReq) Reset()         { *m = DecGoodsNumReq{} }
func (m *DecGoodsNumReq) String() string { return proto.CompactTextString(m) }
func (*DecGoodsNumReq) ProtoMessage()    {}
func (*DecGoodsNumReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b63c4ddc3f3c0c, []int{4}
}

func (m *DecGoodsNumReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecGoodsNumReq.Unmarshal(m, b)
}
func (m *DecGoodsNumReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecGoodsNumReq.Marshal(b, m, deterministic)
}
func (m *DecGoodsNumReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecGoodsNumReq.Merge(m, src)
}
func (m *DecGoodsNumReq) XXX_Size() int {
	return xxx_messageInfo_DecGoodsNumReq.Size(m)
}
func (m *DecGoodsNumReq) XXX_DiscardUnknown() {
	xxx_messageInfo_DecGoodsNumReq.DiscardUnknown(m)
}

var xxx_messageInfo_DecGoodsNumReq proto.InternalMessageInfo

func (m *DecGoodsNumReq) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *DecGoodsNumReq) GetGoodsNum() int64 {
	if m != nil {
		return m.GoodsNum
	}
	return 0
}

type DecGoodsNumRsp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecGoodsNumRsp) Reset()         { *m = DecGoodsNumRsp{} }
func (m *DecGoodsNumRsp) String() string { return proto.CompactTextString(m) }
func (*DecGoodsNumRsp) ProtoMessage()    {}
func (*DecGoodsNumRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b63c4ddc3f3c0c, []int{5}
}

func (m *DecGoodsNumRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecGoodsNumRsp.Unmarshal(m, b)
}
func (m *DecGoodsNumRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecGoodsNumRsp.Marshal(b, m, deterministic)
}
func (m *DecGoodsNumRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecGoodsNumRsp.Merge(m, src)
}
func (m *DecGoodsNumRsp) XXX_Size() int {
	return xxx_messageInfo_DecGoodsNumRsp.Size(m)
}
func (m *DecGoodsNumRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_DecGoodsNumRsp.DiscardUnknown(m)
}

var xxx_messageInfo_DecGoodsNumRsp proto.InternalMessageInfo

type ListGoodsReq struct {
	PageNo               int64    `protobuf:"varint,1,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	PageSize             int64    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGoodsReq) Reset()         { *m = ListGoodsReq{} }
func (m *ListGoodsReq) String() string { return proto.CompactTextString(m) }
func (*ListGoodsReq) ProtoMessage()    {}
func (*ListGoodsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b63c4ddc3f3c0c, []int{6}
}

func (m *ListGoodsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGoodsReq.Unmarshal(m, b)
}
func (m *ListGoodsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGoodsReq.Marshal(b, m, deterministic)
}
func (m *ListGoodsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGoodsReq.Merge(m, src)
}
func (m *ListGoodsReq) XXX_Size() int {
	return xxx_messageInfo_ListGoodsReq.Size(m)
}
func (m *ListGoodsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGoodsReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListGoodsReq proto.InternalMessageInfo

func (m *ListGoodsReq) GetPageNo() int64 {
	if m != nil {
		return m.PageNo
	}
	return 0
}

func (m *ListGoodsReq) GetPageSize() int64 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListGoodsRsp struct {
	Goods                []*ListGoodsRsp_Goods `protobuf:"bytes,1,rep,name=goods,proto3" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListGoodsRsp) Reset()         { *m = ListGoodsRsp{} }
func (m *ListGoodsRsp) String() string { return proto.CompactTextString(m) }
func (*ListGoodsRsp) ProtoMessage()    {}
func (*ListGoodsRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b63c4ddc3f3c0c, []int{7}
}

func (m *ListGoodsRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGoodsRsp.Unmarshal(m, b)
}
func (m *ListGoodsRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGoodsRsp.Marshal(b, m, deterministic)
}
func (m *ListGoodsRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGoodsRsp.Merge(m, src)
}
func (m *ListGoodsRsp) XXX_Size() int {
	return xxx_messageInfo_ListGoodsRsp.Size(m)
}
func (m *ListGoodsRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGoodsRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ListGoodsRsp proto.InternalMessageInfo

func (m *ListGoodsRsp) GetGoods() []*ListGoodsRsp_Goods {
	if m != nil {
		return m.Goods
	}
	return nil
}

type ListGoodsRsp_Goods struct {
	GoodsId              int64    `protobuf:"varint,1,opt,name=goods_id,json=goodsId,proto3" json:"goods_id,omitempty"`
	GoodsNum             int64    `protobuf:"varint,2,opt,name=goods_num,json=goodsNum,proto3" json:"goods_num,omitempty"`
	GoodsName            string   `protobuf:"bytes,3,opt,name=goods_name,json=goodsName,proto3" json:"goods_name,omitempty"`
	GoodsDetail          string   `protobuf:"bytes,4,opt,name=goods_detail,json=goodsDetail,proto3" json:"goods_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListGoodsRsp_Goods) Reset()         { *m = ListGoodsRsp_Goods{} }
func (m *ListGoodsRsp_Goods) String() string { return proto.CompactTextString(m) }
func (*ListGoodsRsp_Goods) ProtoMessage()    {}
func (*ListGoodsRsp_Goods) Descriptor() ([]byte, []int) {
	return fileDescriptor_46b63c4ddc3f3c0c, []int{7, 0}
}

func (m *ListGoodsRsp_Goods) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListGoodsRsp_Goods.Unmarshal(m, b)
}
func (m *ListGoodsRsp_Goods) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListGoodsRsp_Goods.Marshal(b, m, deterministic)
}
func (m *ListGoodsRsp_Goods) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListGoodsRsp_Goods.Merge(m, src)
}
func (m *ListGoodsRsp_Goods) XXX_Size() int {
	return xxx_messageInfo_ListGoodsRsp_Goods.Size(m)
}
func (m *ListGoodsRsp_Goods) XXX_DiscardUnknown() {
	xxx_messageInfo_ListGoodsRsp_Goods.DiscardUnknown(m)
}

var xxx_messageInfo_ListGoodsRsp_Goods proto.InternalMessageInfo

func (m *ListGoodsRsp_Goods) GetGoodsId() int64 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *ListGoodsRsp_Goods) GetGoodsNum() int64 {
	if m != nil {
		return m.GoodsNum
	}
	return 0
}

func (m *ListGoodsRsp_Goods) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *ListGoodsRsp_Goods) GetGoodsDetail() string {
	if m != nil {
		return m.GoodsDetail
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateGoodsReq)(nil), "store.service.v1.CreateGoodsReq")
	proto.RegisterType((*CreateGoodsRsp)(nil), "store.service.v1.CreateGoodsRsp")
	proto.RegisterType((*IncGoodsNumReq)(nil), "store.service.v1.IncGoodsNumReq")
	proto.RegisterType((*IncGoodsNumRsp)(nil), "store.service.v1.IncGoodsNumRsp")
	proto.RegisterType((*DecGoodsNumReq)(nil), "store.service.v1.DecGoodsNumReq")
	proto.RegisterType((*DecGoodsNumRsp)(nil), "store.service.v1.DecGoodsNumRsp")
	proto.RegisterType((*ListGoodsReq)(nil), "store.service.v1.ListGoodsReq")
	proto.RegisterType((*ListGoodsRsp)(nil), "store.service.v1.ListGoodsRsp")
	proto.RegisterType((*ListGoodsRsp_Goods)(nil), "store.service.v1.ListGoodsRsp.Goods")
}

func init() { proto.RegisterFile("api/store/service/v1/store.proto", fileDescriptor_46b63c4ddc3f3c0c) }

var fileDescriptor_46b63c4ddc3f3c0c = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x93, 0xc1, 0x4f, 0xc2, 0x30,
	0x14, 0xc6, 0x33, 0x26, 0xe0, 0x1e, 0x84, 0x90, 0x5e, 0x80, 0x19, 0xc9, 0x5c, 0x3c, 0x90, 0x98,
	0x8c, 0x80, 0x37, 0xbd, 0x29, 0x89, 0x12, 0xcd, 0x12, 0xc7, 0xcd, 0x0b, 0x99, 0xec, 0x85, 0x2c,
	0x71, 0xb4, 0xac, 0x63, 0x07, 0x6e, 0xfe, 0x81, 0xfa, 0x37, 0x99, 0xb6, 0x48, 0x36, 0x40, 0x96,
	0x18, 0x6f, 0xed, 0xd7, 0xaf, 0xbf, 0xbe, 0xf6, 0x7b, 0x05, 0xcb, 0x67, 0x61, 0x9f, 0x27, 0x34,
	0xc6, 0x3e, 0xc7, 0x38, 0x0d, 0x67, 0xd8, 0x4f, 0x07, 0x4a, 0x70, 0x58, 0x4c, 0x13, 0x4a, 0x9a,
	0x6a, 0xb2, 0x59, 0x75, 0xd2, 0x81, 0xed, 0x41, 0xe3, 0x3e, 0x46, 0x3f, 0xc1, 0x07, 0x4a, 0x03,
	0xee, 0xe1, 0x92, 0x9c, 0x03, 0xcc, 0xc5, 0x78, 0xba, 0xf0, 0x23, 0x6c, 0x6b, 0x96, 0xd6, 0x33,
	0x3c, 0x43, 0x2a, 0xae, 0x1f, 0x21, 0xb9, 0x80, 0xba, 0x5a, 0x0e, 0x30, 0xf1, 0xc3, 0xf7, 0x76,
	0x49, 0x1a, 0x6a, 0x52, 0x1b, 0x49, 0xc9, 0xbe, 0xca, 0x33, 0x39, 0x23, 0x1d, 0x38, 0x55, 0x9b,
	0xc2, 0x40, 0x12, 0x75, 0xaf, 0x2a, 0xe7, 0xe3, 0xc0, 0x7e, 0x84, 0xc6, 0x78, 0x31, 0x93, 0x4e,
	0x77, 0x15, 0x89, 0x02, 0x7e, 0x37, 0x93, 0x33, 0x30, 0x36, 0xb5, 0xad, 0x22, 0x79, 0xb2, 0xee,
	0x29, 0xaf, 0xbb, 0x8a, 0xec, 0x66, 0x9e, 0xc4, 0x99, 0x60, 0x8f, 0xf0, 0xbf, 0xd8, 0x59, 0x12,
	0x67, 0xf6, 0x08, 0xea, 0xcf, 0x21, 0x4f, 0xb6, 0xcf, 0xd6, 0x82, 0x2a, 0xf3, 0xe7, 0x38, 0x5d,
	0xd0, 0x0d, 0xb8, 0x22, 0xa6, 0x2e, 0x15, 0x5c, 0xb9, 0xc0, 0xc3, 0x35, 0xfe, 0x70, 0x85, 0x30,
	0x09, 0xd7, 0x68, 0x7f, 0x69, 0x59, 0x0c, 0x67, 0xe4, 0x06, 0xca, 0xf2, 0xd0, 0xb6, 0x66, 0xe9,
	0xbd, 0xda, 0xf0, 0xd2, 0xd9, 0x4d, 0xcc, 0xc9, 0xda, 0x1d, 0x35, 0x50, 0x5b, 0xcc, 0x0f, 0x0d,
	0xca, 0x52, 0xf8, 0xeb, 0x35, 0x77, 0xb2, 0xd7, 0x8b, 0xb2, 0x3f, 0xd9, 0xcb, 0x7e, 0xf8, 0x59,
	0x82, 0xf2, 0x44, 0x94, 0x4c, 0x5e, 0xa0, 0x96, 0xe9, 0x02, 0x62, 0xed, 0xdf, 0x24, 0xdf, 0x78,
	0x66, 0x81, 0x83, 0x33, 0x81, 0xcc, 0x24, 0x7c, 0x08, 0x99, 0x6f, 0x25, 0xb3, 0xc0, 0xc1, 0x19,
	0x79, 0x02, 0x63, 0xfb, 0xa0, 0xa4, 0x7b, 0xec, 0xb5, 0x71, 0x69, 0x76, 0x8f, 0xa7, 0x21, 0xea,
	0xcb, 0x74, 0xc9, 0xa1, 0xfa, 0xf2, 0xed, 0x68, 0x16, 0x38, 0x38, 0xbb, 0xeb, 0xbc, 0xb6, 0x0e,
	0xfd, 0xea, 0xdb, 0x74, 0xf0, 0x56, 0x91, 0x7f, 0xfa, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x38,
	0x02, 0x81, 0x46, 0xf7, 0x03, 0x00, 0x00,
}
